[project]
name = "sentiment-analyzer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "google-generativeai>=0.8.6",
    "litellm>=1.81.8",
    "pydantic>=2.12.5",
    "python-dotenv>=1.2.1",
]
